### ISSUE TITLE
NPE when pressing the button Go (on start up screen)

### ISSUE THREAD

**Issue by MathiasSeguy-Android2EE** [devoxx/AndroidMobileApp#6]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.devoxx, PID: 28457
                  java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.devoxx.connection.cfp.model.ConferenceApiModel.cfpURL' on a null object reference
                      at com.devoxx.android.activity.SelectorActivity.onGoClick(SelectorActivity.java:177)
                      at com.devoxx.android.activity.SelectorActivity_$1.onClick(SelectorActivity_.java:110)
                      at android.view.View.performClick(View.java:5204)
                      at android.view.View$PerformClick.run(View.java:21155)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5422)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/QCALOG: [MessageQ] ProcessNewMessage: [LOWI-SERVER] unknown deliver target [OS-Agent]

Nexus 5X / Android 6.0.1

**Comment by jmodrako** [comment]
Thanks @MathiasSeguy-Android2EE for the info. We've already fixed this issue, today we will update an app ;)
